# Generated by Django 5.2.1 on 2025-09-17 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Админ'), ('stockkeeper', 'Складчик'), ('manager', 'Менеджер'), ('cashier', 'Кассир')], default='cashier', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plain_password', models.CharField(blank=True, help_text='Пароль в открытом виде (только для администраторов)', max_length=128, null=True, verbose_name='Пароль')),
                ('accessible_stores', models.ManyToManyField(blank=True, help_text='Магазины, к которым сотрудник имеет доступ', null=True, related_name='accessible_employees', to='stores.store', verbose_name='Доступные магазины')),
                ('store', models.ForeignKey(blank=True, help_text='Магазин, к которому привязан сотрудник', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='stores.store', verbose_name='Магазин')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
