# Generated by Django 5.2.1 on 2025-09-17 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_quantity_sold', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Общее количество проданного')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая выручка')),
                ('products_count', models.PositiveIntegerField(default=0, verbose_name='Количество товаров в категории')),
                ('transactions_count', models.PositiveIntegerField(default=0, verbose_name='Количество транзакций')),
                ('unique_products_sold', models.PositiveIntegerField(default=0, verbose_name='Уникальных товаров продано')),
                ('average_transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Средняя сумма транзакции')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='inventory.productcategory', verbose_name='Категория')),
                ('store', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Аналитика категорий',
                'verbose_name_plural': 'Аналитика категорий',
                'ordering': ['-date', 'category__name'],
                'unique_together': {('store', 'date', 'category')},
            },
        ),
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Сумма покупок')),
                ('transaction_count', models.PositiveIntegerField(default=0, verbose_name='Количество транзакций')),
                ('debt_added', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Добавлено долга')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_analytics', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='customers.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Аналитика клиента',
                'verbose_name_plural': 'Аналитика клиентов',
                'ordering': ['-date'],
                'unique_together': {('customer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('quantity_sold', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Продано единиц')),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Выручка')),
                ('unit_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип единицы измерения')),
                ('unit_display', models.CharField(blank=True, max_length=20, null=True, verbose_name='Отображение единицы')),
                ('size_info', models.JSONField(blank=True, help_text='JSON с данными о размере товара на момент продажи', null=True, verbose_name='Информация о размере')),
                ('average_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Средняя цена за единицу')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_analytics', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='inventory.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Аналитика товара',
                'verbose_name_plural': 'Аналитика товаров',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'product'], name='analytics_p_date_c15a74_idx'), models.Index(fields=['unit_type', 'date'], name='analytics_p_unit_ty_e04d86_idx')],
                'unique_together': {('product', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('total_items_sold', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('card', 'Карта'), ('debt', 'В долг')], max_length=20)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_summaries', to=settings.AUTH_USER_MODEL, verbose_name='Кассир')),
                ('store', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Сводка по продажам',
                'verbose_name_plural': 'Сводки по продажам',
                'ordering': ['-date'],
                'unique_together': {('store', 'date', 'payment_method')},
            },
        ),
        migrations.CreateModel(
            name='SizeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('size_name', models.CharField(max_length=50, verbose_name='Название размера')),
                ('dimension1', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Параметр 1')),
                ('dimension2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Параметр 2')),
                ('dimension3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Параметр 3')),
                ('dimension1_label', models.CharField(blank=True, max_length=50, null=True)),
                ('dimension2_label', models.CharField(blank=True, max_length=50, null=True)),
                ('dimension3_label', models.CharField(blank=True, max_length=50, null=True)),
                ('total_quantity_sold', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Общее количество проданного')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая выручка')),
                ('products_count', models.PositiveIntegerField(default=0, verbose_name='Количество товаров этого размера')),
                ('transactions_count', models.PositiveIntegerField(default=0, verbose_name='Количество транзакций')),
                ('store', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Аналитика размеров',
                'verbose_name_plural': 'Аналитика размеров',
                'ordering': ['-date', 'size_name'],
                'unique_together': {('store', 'date', 'size_name')},
            },
        ),
        migrations.CreateModel(
            name='UnitAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('unit_type', models.CharField(max_length=50, verbose_name='Тип единицы измерения')),
                ('unit_display', models.CharField(max_length=20, verbose_name='Отображение единицы')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Пользовательская единица')),
                ('total_quantity_sold', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Общее количество проданного')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая выручка')),
                ('products_count', models.PositiveIntegerField(default=0, verbose_name='Количество товаров с этой единицей')),
                ('transactions_count', models.PositiveIntegerField(default=0, verbose_name='Количество транзакций')),
                ('average_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Средняя цена за единицу')),
                ('store', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Аналитика единиц измерения',
                'verbose_name_plural': 'Аналитика единиц измерения',
                'ordering': ['-date', 'unit_display'],
                'unique_together': {('store', 'date', 'unit_type', 'unit_display')},
            },
        ),
    ]
