# Generated by Django 5.2.1 on 2025-09-20 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_salessummary_payment_method'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('supplier', models.CharField(db_index=True, max_length=255, verbose_name='Поставщик')),
                ('total_quantity_sold', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Общее количество проданного')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая выручка')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая себестоимость')),
                ('total_margin', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая маржа')),
                ('products_count', models.PositiveIntegerField(default=0, verbose_name='Количество товаров от поставщика')),
                ('transactions_count', models.PositiveIntegerField(default=0, verbose_name='Количество транзакций')),
                ('unique_products_sold', models.PositiveIntegerField(default=0, verbose_name='Уникальных товаров продано')),
                ('average_margin_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Средняя маржа (%)')),
                ('turnover_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Коэффициент оборачиваемости')),
                ('store', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Аналитика поставщиков',
                'verbose_name_plural': 'Аналитика поставщиков',
                'ordering': ['-date', 'supplier'],
                'indexes': [models.Index(fields=['supplier', 'date'], name='analytics_s_supplie_042d09_idx')],
                'unique_together': {('store', 'date', 'supplier')},
            },
        ),
    ]
