# Generated by Django 5.2.1 on 2025-09-20 10:15

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_supplieranalytics'),
        ('inventory', '0003_financialsummary_stockhistory'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_opened', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Открытие смены')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Текущий баланс')),
                ('target_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Целевой баланс')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('is_open', models.BooleanField(default=True, verbose_name='Смена открыта')),
                ('financial_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_registers', to='inventory.financialsummary', verbose_name='Дневная сводка')),
                ('store', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
                'ordering': ['-date_opened'],
                'unique_together': {('store', 'date_opened')},
            },
        ),
    ]
