# Generated by Django 5.2.1 on 2025-09-20 10:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_cashregister'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='closed_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Фактический баланс при закрытии смены', max_digits=12, verbose_name='Баланс при закрытии'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='discrepancy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Расхождение'),
        ),
        migrations.CreateModel(
            name='CashHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('OPEN_SHIFT', 'Открытие смены'), ('ADD_CASH', 'Добавление наличных'), ('WITHDRAW', 'Снятие наличных'), ('CLOSE_SHIFT', 'Закрытие смены'), ('CORRECTION', 'Корректировка')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='analytics.cashregister')),
                ('store', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='stores.store', verbose_name='Магазин')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Операция кассы',
                'verbose_name_plural': 'История кассы',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='cashregister',
            name='cash_history',
            field=models.ManyToManyField(blank=True, related_name='cash_registers', to='analytics.cashhistory'),
        ),
        migrations.AddIndex(
            model_name='cashhistory',
            index=models.Index(fields=['cash_register', 'timestamp'], name='analytics_c_cash_re_0eb620_idx'),
        ),
    ]
