# Generated by Django 5.2.1 on 2025-09-20 12:14

import analytics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_cashregister_closed_at_cashregister_closed_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitanalytics',
            name='product_ids',
            field=models.JSONField(default=analytics.models.default_product_ids, verbose_name='ID товаров'),
        ),
        migrations.AlterField(
            model_name='unitanalytics',
            name='products_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество уникальных товаров'),
        ),
    ]
