# Generated by Django 5.2.1 on 2025-09-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название шаблона', max_length=100, unique=True)),
                ('content', models.TextField(help_text='Содержимое SMS-шаблона. Доступные переменные: @ - имя покупателя, $ - сумма долга')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Шаблон',
                'verbose_name_plural': 'SMS Шаблоны',
                'ordering': ['-created_at'],
            },
        ),
    ]
