# Generated by Django 5.2.1 on 2025-09-20 08:14

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productbatchattribute'),
        ('stores', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('cash_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfer_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debt_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_transactions', models.IntegerField(default=0)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_transaction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unique_customers', models.IntegerField(default=0)),
                ('repeat_customers', models.IntegerField(default=0)),
                ('customer_retention_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_margin', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('top_cashier_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summaries', to='stores.store')),
                ('top_cashier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'store'], name='inventory_f_date_078649_idx'), models.Index(fields=['store', 'date'], name='inventory_f_store_i_df115d_idx')],
                'unique_together': {('date', 'store')},
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('date_only', models.DateField(auto_now_add=True, db_index=True)),
                ('quantity_before', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity_after', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity_change', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('operation_type', models.CharField(choices=[('INCOMING', 'Поступление'), ('SALE', 'Продажа'), ('RETURN', 'Возврат'), ('CORRECTION', 'Корректировка'), ('EXPIRATION', 'Списание'), ('TRANSFER', 'Перемещение'), ('REVALUATION', 'Переоценка')], db_index=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('attributes_snapshot', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=10)),
                ('purchase_price_at_time', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price_at_time', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_automatic', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_history_entries', to='inventory.productbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='inventory.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sizeinfo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_stock_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['product', 'date_only'], name='inventory_s_product_16a195_idx'), models.Index(fields=['store', 'date_only'], name='inventory_s_store_i_aa38da_idx'), models.Index(fields=['timestamp'], name='inventory_s_timesta_e2979e_idx'), models.Index(fields=['operation_type', 'date_only'], name='inventory_s_operati_f9580a_idx')],
            },
        ),
    ]
