# Generated by Django 5.2.1 on 2025-09-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_financialsummary_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='supplier_country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Старана поставщика'),
        ),
    ]
