# Generated by Django 5.2.1 on 2025-09-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productbatch_supplier_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='purchase_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена закупки в USD'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='purchase_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Курс покупки USD'),
        ),
    ]
