# Generated by Django 5.2.1 on 2025-09-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_exchangerate_financialsummary_grand_total_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsummary',
            name='card_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='financialsummary',
            name='cash_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
