# Generated by Django 5.2.1 on 2025-09-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_financialsummary_card_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialsummary',
            name='grand_total_usd',
        ),
        migrations.RemoveField(
            model_name='financialsummary',
            name='total_margin_usd',
        ),
        migrations.RemoveField(
            model_name='financialsummary',
            name='usd_rate',
        ),
    ]
