# Generated by Django 5.2.1 on 2025-09-29 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_financialsummary_grand_total_usd_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documetn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия договора')),
                ('date_from', models.DateField(verbose_name='Дата начала действия')),
                ('date_to', models.DateField(verbose_name='Дата окончание')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загруский')),
                ('store', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договор',
                'ordering': ['-created_at'],
            },
        ),
    ]
