# Generated by Django 5.2.1 on 2025-09-29 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_documetn'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documetn',
            new_name='Document',
        ),
        migrations.AddField(
            model_name='product',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.document', verbose_name='Договор'),
        ),
    ]
