# Generated by Django 5.2.1 on 2025-09-19 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма картой (для гибридной оплаты)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма наличными (для гибридной оплаты)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма переводом (для гибридной оплаты)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('card', 'Карта'), ('debt', 'В долг'), ('hybrid', 'Гибридная оплата')], default='cash', max_length=20),
        ),
    ]
