# Generated by Django 5.2.1 on 2025-09-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_cashregister_closed_at_cashregister_closed_balance_and_more'),
        ('sales', '0002_transaction_card_amount_transaction_cash_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cash_register',
            field=models.ForeignKey(blank=True, help_text='Касса, через которую прошла продажа (если наличные)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='analytics.cashregister', verbose_name='Касса (смена)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cash_register_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время операции на кассе'),
        ),
    ]
