# Generated by Django 5.2.1 on 2025-09-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_transaction_cash_register_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
